language: java
jdk: oraclejdk8

before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
- echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

install: true

script: 
  mvn --settings travis/settings.xml clean install -DskipITs=false -DskipTests=false -Dgpg.skip -Dmaven.javadoc.skip=true  -B -V

deploy:
  -
    provider: script
    script: "mvn --settings travis/settings.xml versions:set -DnewVersion=${TRAVIS_TAG} && mvn --settings travis/settings.xml clean deploy -DskipITs=true -DskipTests=true -B -U -P release"
    on:
      tags: true
